version: '3.8'

services:
  db:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: ${DB_PASSWORD}
      ACCEPT_EULA: "Y"
      MSSQL_TCP_PORT: 1433
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
    networks:
      - app-network

  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - app-network
    env_file:
      - .env
    command: sh -c "sleep 15 && ./main"  # Задержка перед запуском приложения

volumes:
  mssql_data:

networks:
  app-network: