version: '3.8'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    platform: linux/amd64
    environment:
      SA_PASSWORD: ${DB_PASSWORD}
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
    networks:
      - app-network

  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - app-network
    command: sh -c "sleep 10 && ./main"

volumes:
  mssql_data:

networks:
  app-network: