name: Go CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22

      - name: Install Docker Compose
        run: sudo apt-get install -y docker-compose

      - name: Run Docker Compose
        env:
          DB_USER: sa
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_HOST: localhost
          DB_PORT: 1433
          DB_NAME: testdb
        run: |
          docker-compose up -d --build