name : GO CI/CD

on:
  push:
    branches:
      - main
    pull_request:
      branches:
        - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      db:
        image: mcr.microsoft.com/mssql/server
        env:
          SA_PASSWORD: ${{ secrets.DB_PASSWORD }}
          ACCEPT_EULA: "Y"
          MSSQL_TCP_PORT: 1433
        ports:
          - 1433:1433
        
    steps:
      # Клонируем репозиторий
      - name: Checkout code
        uses: actions/checkout@v3
      
      # Устанавливаем GO
      - name: Set up GO
        uses: actions/setup-go@v4
        with:
          go-version: 1.22
      
      # Устанавливаем зависимости
      - name: Install dependencies
        run: go mod download

      # Ждем готовности SQL server
      - name: Wait for SQL server
        run: sleep 10

      # Собираем приложение
      - name: Build Go application
        run: go build -o main .

      # Запуск приложения
      - name: Run the application
        run: ./main &
