name: Go CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      sqlserver:
        image: mcr.microsoft.com/mssql/server
        ports:
          - 1433:1433
        env:
          SA_PASSWORD: ${{ secrets.DB_PASSWORD }}
          ACCEPT_EULA: "Y"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up GO
        uses: actions/setup-go@v4
        with:
          go-version: 1.22

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
          
      - name: Set up env variables
        run: echo "DB_HOST=localhost" >> $GITHUB_ENV
        run: echo "DB_PORT=1433" >> $GITHUB_ENV
        run: echo "DB_USER=sa" >> $GITHUB_ENV
        run: echo "DB_NAME=testdb" >> $GITHUB_ENV

      - name: Build the project
        run: go build -v ./...

      - name: Run application
        run: docker-compose up -d